services:
  # Service to build the Spring Boot Docker image using Maven
  builder:
    image: maven:3.8.4-openjdk-11-slim
    volumes:
      - ./booking-backend:/app
    working_dir: /app
    command: ./mvnw spring-boot:build-image

  app:
    image: 'my-application:latest'  #  'docker.io/library/my-application:latest'
    ports:
      - "8080:8080"  # Map container port 8080 to host port 8080
    depends_on:
      - builder  
    network_mode: host


networks:
  default:
    name: mynetwork  # Optionally give a custom network name
