version: '3.8'

services:
  frontend:
    image: stenmartinlaane/tire-change-app-frontend:latest
    container_name: tire-change-frontend
    ports:
      - "3000:3000"  
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8080 
    depends_on:
      - backend

  backend:
    image: stenmartinlaane/tire-change-app-backend:latest
    container_name: tire-change-backend
    ports:
      - "8080:8080" 
    environment:
      - SPRING_PROFILES_ACTIVE=prod
