import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';

import StateComponent from "../context/StateComponent";

import { ToastContainer } from "react-toastify";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { MantineProvider } from "@mantine/core";
import { ColorSchemeScript } from '@mantine/core';
import { Suspense } from 'react';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
    <body>
    <Suspense fallback={<div>Loading...</div>}>
    <div className="bg-white w-full h-screen border-full flex flex-col">
          <StateComponent>
            <div className="flex flex-col w-full h-full flex-grow">
              <main className="grow flex-1 w-full h-50 bg-background py-4">
              <MantineProvider>
                 { children}
                </MantineProvider>
              </main>
            </div>
          </StateComponent>
      </div>
    </Suspense>
      <ToastContainer />
    </body>
  </html>
  );
}
